name: squarealfa_validation_example
description: Example for squarealfa_validation_generator
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  squarealfa_entity_annotations: ^2.0.1
  decimal: ^2.1.0
  fixnum: ^1.0.0

dev_dependencies:
  squarealfa_entity_generator: ^2.0.1
  build_runner: ^2.1.7
  build_verify: ^3.0.0
  lints: ^1.0.1
  test: ^1.16.8
