name: proto_mapper_example
description: proto_annotations and proto_generator packages demonstration project
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/proto_mapper/example
repository: https://gitlab.com/squarealfa/dart_framework
version: 2.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  proto_annotations: ^2.0.7

dev_dependencies:
  lints: ^1.0.1
  test: ^1.14.4
  proto_generator: ^3.0.4
  build_runner: ^2.1.2
