name: map_mapper_example
description: map_mapper_annotations and map_mapper_generator packages demonstration project
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/map_mapper/example
repository: https://gitlab.com/squarealfa/dart_framework
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  map_mapper_annotations: ^3.0.4

dev_dependencies:
  map_mapper_generator: ^3.0.5
  lints: ^1.0.1
  build_runner: ^2.0.0
  test: ^1.20.1
