name: map_mapper_generator_test
description: A starting point for Dart libraries or applications.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  map_mapper_generator:
    path: ../map_mapper_generator
  decimal: ^1.0.0
  fixnum: ^1.0.0
  mongo_dart: ^0.7.0+1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^2.0.0
  lints: ^1.0.1
  test: ^1.17.12
  
  
## until mongo_dart upgrades its depedencies to ration: 2.0.0, we cannot test with the latest version 
## of map_mapper_generator

## We need to consider implementing a mongodb driver over RestHeart (Rest API for Dart) instead of 
## depending on mongo_dart. With RestHeart we will get MongoDB transaction support.

# dependency_overrides:
#   map_mapper_generator: 2.0.0