name: example_model
description: Complete model demonstration project
homepage: https://github.com/squarealfa/dart_framework/tree/main/proto_mapper/proto_mapper_example
repository: https://github.com/squarealfa/dart_framework
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  proto_annotations: ^2.0.2
  map_mapper_annotations: ^3.0.1
  

dev_dependencies:
  build_runner: ^2.1.2
  lints: ^1.0.1
  map_mapper_generator: ^3.0.1
  proto_generator: ^3.0.1
  test: ^1.17.12
