name: mongo_repository
description: Concrete implementation of the nosql_repository package for the ArangoDB database.
repository: https://github.com/squarealfa/dart_framework
homepage: https://github.com/squarealfa/dart_framework/tree/main/mongo_repository
version: 2.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mongo_dart: ^0.7.2
  nosql_repository: ^2.0.0
  squarealfa_security: ^2.0.0
  tuple: ^2.0.0

dev_dependencies:
  
  test: ^1.17.0
  nosql_repository_tests:
    path: ../nosql_repository/test
  lints: ^1.0.1
