name: nosql_repository
description: Repository pattern oriented towards NoSQL databases. This package defines the interfaces to be used by an application to access a database, namely for CRUD and searching.
repository: https://gitlab.com/squarealfa/dart_framework
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/nosql_repository
version: 2.1.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  squarealfa_security: ^2.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.0