name: defaults_provider_example
description: defaults_provider_annotations and defaults_provider_generator
  packages demonstration project
homepage: https://github.com/squarealfa/dart_framework/tree/main/defaults_provider/defaults_provider_example
repository: https://github.com/squarealfa/dart_framework
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  defaults_provider_annotations: ^2.0.0

dev_dependencies:
   

  build_runner: ^2.0.0
  defaults_provider_generator: ^2.0.1
  lints: ^1.0.1
  test: ^1.20.1
