name: squarealfa_entity_generator
description:
  Code generators that augment classes that are meant to be used as business entities
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/entity/entity_generator
repository: https://gitlab.com/squarealfa/dart_framework
version: 2.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  analyzer: ^3.0.0
  build: ^2.0.0
  decimal: ^2.1.0
  source_gen: ^1.0.0
  squarealfa_entity_annotations: ^2.1.0
  squarealfa_generators_common: ^2.2.0
  tuple: ^2.0.0

dev_dependencies:
  lints: ^1.0.1
