name: map_mapper_annotations
description: 
  Contains annotations and mappers to allow the mapping between PODOs and Map<String, dynamic> maps 
  used to interact with document databases
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/map_mapper/map_mapper_annotations
repository: https://gitlab.com/squarealfa/dart_framework
version: 3.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  squarealfa_common_types: ^1.1.0

dev_dependencies:
  lints: ^1.0.1

# dependency_overrides:
#   squarealfa_common_types:
#     path: ../../common_types