name: squarealfa_generators_common
description: This package provides a set of helpers and extensions to facilitate the reflection over classes that serving as the basis for code generation.
homepage: https://gitlab.com/squarealfa/dart_framework/-/tree/main/generators_common
repository: https://gitlab.com/squarealfa/dart_framework
version: 2.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: ^1.0.0
  analyzer: ^3.0.0
  build: ^2.0.0
  build_resolvers: ^2.0.0
  build_test: ^2.0.0
  squarealfa_common_types: ^1.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1

# dependency_overrides:
#   squarealfa_common_types:
#     path: ../common_types